from pathlib import Path
from dataclasses import dataclass

CONFIGURATION_DIRECTORY: str
PERSISTENT_DATA_DIRECTORY: str
DATASET_MARKER_FILENAME: str

@dataclass(frozen=True, slots=True)
class ProjectData:
    root: Path
    project_name: str
    @property
    def path(self) -> Path: ...
    @property
    def configuration_directory(self) -> Path: ...
    def animal(self, animal_id: str) -> AnimalData: ...
    def for_root(self, root: Path) -> ProjectData: ...
    def experiment_configs(self) -> tuple[Path, ...]: ...
    def exists(self) -> bool: ...

@dataclass(frozen=True, slots=True)
class AnimalData:
    root: Path
    project_name: str
    animal_id: str
    @property
    def path(self) -> Path: ...
    @property
    def project(self) -> ProjectData: ...
    @property
    def persistent_data_path(self) -> Path: ...
    def session_path(self, session_name: str) -> Path: ...
    def for_root(self, root: Path) -> AnimalData: ...
    def exists(self) -> bool: ...
