from dataclasses import dataclass

from ataraxis_data_structures import YamlConfig

@dataclass
class MesoscopeHardwareState(YamlConfig):
    cm_per_pulse: float | None = ...
    maximum_brake_strength: float | None = ...
    minimum_brake_strength: float | None = ...
    lick_threshold: int | None = ...
    valve_scale_coefficient: float | None = ...
    valve_nonlinearity_exponent: float | None = ...
    torque_per_adc_unit: float | None = ...
    screens_initially_on: bool | None = ...
    recorded_mesoscope_ttl: bool | None = ...
    delivered_gas_puffs: bool | None = ...
    system_state_codes: dict[str, int] | None = ...

@dataclass
class LickTrainingDescriptor(YamlConfig):
    experimenter: str
    mouse_weight_g: float
    minimum_reward_delay_s: int = ...
    maximum_reward_delay_s: int = ...
    maximum_water_volume_ml: float = ...
    maximum_training_time_min: int = ...
    maximum_unconsumed_rewards: int = ...
    water_reward_size_ul: float = ...
    reward_tone_duration_ms: int = ...
    dispensed_water_volume_ml: float = ...
    pause_dispensed_water_volume_ml: float = ...
    experimenter_given_water_volume_ml: float = ...
    preferred_session_water_volume_ml: float = ...
    incomplete: bool = ...
    experimenter_notes: str = ...

@dataclass
class RunTrainingDescriptor(YamlConfig):
    experimenter: str
    mouse_weight_g: float
    final_run_speed_threshold_cm_s: float = ...
    final_run_duration_threshold_s: float = ...
    initial_run_speed_threshold_cm_s: float = ...
    initial_run_duration_threshold_s: float = ...
    increase_threshold_ml: float = ...
    run_speed_increase_step_cm_s: float = ...
    run_duration_increase_step_s: float = ...
    maximum_water_volume_ml: float = ...
    maximum_training_time_min: int = ...
    maximum_unconsumed_rewards: int = ...
    maximum_idle_time_s: float = ...
    water_reward_size_ul: float = ...
    reward_tone_duration_ms: int = ...
    dispensed_water_volume_ml: float = ...
    pause_dispensed_water_volume_ml: float = ...
    experimenter_given_water_volume_ml: float = ...
    preferred_session_water_volume_ml: float = ...
    incomplete: bool = ...
    experimenter_notes: str = ...

@dataclass
class MesoscopeExperimentDescriptor(YamlConfig):
    experimenter: str
    mouse_weight_g: float
    maximum_unconsumed_rewards: int = ...
    dispensed_water_volume_ml: float = ...
    pause_dispensed_water_volume_ml: float = ...
    experimenter_given_water_volume_ml: float = ...
    preferred_session_water_volume_ml: float = ...
    incomplete: bool = ...
    experimenter_notes: str = ...

@dataclass
class WindowCheckingDescriptor(YamlConfig):
    experimenter: str
    surgery_quality: int = ...
    incomplete: bool = ...
    experimenter_notes: str = ...

@dataclass
class ZaberPositions(YamlConfig):
    headbar_z: int = ...
    headbar_pitch: int = ...
    headbar_roll: int = ...
    lickport_z: int = ...
    lickport_y: int = ...
    lickport_x: int = ...
    wheel_x: int = ...

@dataclass
class MesoscopePositions(YamlConfig):
    mesoscope_x: float = ...
    mesoscope_y: float = ...
    mesoscope_roll: float = ...
    mesoscope_z: float = ...
    mesoscope_fast_z: float = ...
    mesoscope_tip: float = ...
    mesoscope_tilt: float = ...
    laser_power_mw: float = ...
    red_dot_alignment_z: float = ...
