"""Provides data acquisition and processing assets shared between Sollertia platform libraries.

See the `API documentation <https://sollertia-shared-assets-api-docs.netlify.app/>`_ for the description of available
assets. See the `source code repository <https://github.com/Sun-Lab-NBB/sollertia-shared-assets>`_ for more details.

Authors: Ivan Kondratyev (Inkaros), Kushaan Gupta, Natalie Yeung
"""

from ataraxis_base_utilities import console

from .data_classes import (
    RAW_DATA_DIRECTORY,
    CONFIGURATION_DIRECTORY,
    PROCESSED_DATA_DIRECTORY,
    PERSISTENT_DATA_DIRECTORY,
    RawData,
    DrugData,
    AnimalData,
    Directories,
    ImplantData,
    ProjectData,
    SessionData,
    SubjectData,
    SurgeryData,
    RawDataFiles,
    SessionTypes,
    InjectionData,
    ProcedureData,
    ProcessedData,
    ProcessingTrackers,
    RunTrainingDescriptor,
    LickTrainingDescriptor,
    MesoscopeHardwareState,
    WindowCheckingDescriptor,
    MesoscopeExperimentDescriptor,
    filter_sessions,
    iterate_sessions,
    discover_projects,
    discover_sessions,
    validate_directory,
    iter_project_animals,
    get_projects_for_animal,
    parse_session_timestamp,
)
from .configuration import (
    Cue,
    TriggerType,
    GasPuffTrial,
    TaskTemplate,
    VREnvironment,
    TrialStructure,
    ExperimentState,
    WaterRewardTrial,
    AcquisitionSystems,
    MesoscopeExperimentConfiguration,
    get_working_directory,
    set_working_directory,
    get_google_credentials_path,
    set_google_credentials_path,
    get_task_templates_directory,
    set_task_templates_directory,
    create_experiment_configuration,
)

# Ensures console is enabled when this library is imported.
if not console.enabled:
    console.enable()

__all__ = [
    "CONFIGURATION_DIRECTORY",
    "PERSISTENT_DATA_DIRECTORY",
    "PROCESSED_DATA_DIRECTORY",
    "RAW_DATA_DIRECTORY",
    "AcquisitionSystems",
    "AnimalData",
    "Cue",
    "Directories",
    "DrugData",
    "ExperimentState",
    "GasPuffTrial",
    "ImplantData",
    "InjectionData",
    "LickTrainingDescriptor",
    "MesoscopeExperimentConfiguration",
    "MesoscopeExperimentDescriptor",
    "MesoscopeHardwareState",
    "ProcedureData",
    "ProcessedData",
    "ProcessingTrackers",
    "ProjectData",
    "RawData",
    "RawDataFiles",
    "RunTrainingDescriptor",
    "SessionData",
    "SessionTypes",
    "SubjectData",
    "SurgeryData",
    "TaskTemplate",
    "TrialStructure",
    "TriggerType",
    "VREnvironment",
    "WaterRewardTrial",
    "WindowCheckingDescriptor",
    "create_experiment_configuration",
    "discover_projects",
    "discover_sessions",
    "filter_sessions",
    "get_google_credentials_path",
    "get_projects_for_animal",
    "get_task_templates_directory",
    "get_working_directory",
    "iter_project_animals",
    "iterate_sessions",
    "parse_session_timestamp",
    "set_google_credentials_path",
    "set_task_templates_directory",
    "set_working_directory",
    "validate_directory",
]
