"""Provides data acquisition and processing assets shared between Sollertia platform libraries.

See the `API documentation <https://sollertia-shared-assets-api-docs.netlify.app/>`_ for the description of available
assets. See the `source code repository <https://github.com/Sun-Lab-NBB/sollertia-shared-assets>`_ for more details.

Authors: Ivan Kondratyev (Inkaros), Kushaan Gupta, Natalie Yeung
"""

from ataraxis_base_utilities import console

from .enums import (
    ReadAssets,
    SessionTypes,
    CredentialsTypes,
    AcquisitionSystems,
)
from .registries import (
    DESCRIPTOR_REGISTRY,
    READ_ASSET_REGISTRY,
    CREDENTIALS_FILE_REGISTRY,
    SESSION_TYPES_USING_VR_TASK,
    resolve_read_asset,
)
from .credentials import (
    get_credentials,
    set_credentials,
    resolve_credentials_file,
)
from .data_classes import (
    DrugData,
    ImplantData,
    SubjectData,
    SurgeryData,
    InjectionData,
    ProcedureData,
)
from .mesoscope_vr import (
    TrialKind,
    MesoscopeRawData,
    MesoscopeDirectories,
    MesoscopeGasPuffTrial,
    MesoscopeRawDataFiles,
    RunTrainingDescriptor,
    LickTrainingDescriptor,
    MesoscopeHardwareState,
    WindowCheckingDescriptor,
    MesoscopeWaterRewardTrial,
    MesoscopeExperimentDescriptor,
    MesoscopeExperimentConfiguration,
)
from .configuration import (
    CREDENTIALS_DIRECTORY,
    CONFIGURATION_DIRECTORY,
    Cue,
    TriggerType,
    TaskTemplate,
    VREnvironment,
    TrialStructure,
    ExperimentState,
    get_data_root,
    set_data_root,
    get_working_directory,
    set_working_directory,
    get_task_templates_directory,
    set_task_templates_directory,
)
from .data_hierarchy import (
    RAW_DATA_DIRECTORY,
    DATASET_MARKER_FILENAME,
    PROCESSED_DATA_DIRECTORY,
    PERSISTENT_DATA_DIRECTORY,
    RawData,
    AnimalData,
    DatasetData,
    Directories,
    ProjectData,
    SessionData,
    DatasetFiles,
    RawDataFiles,
    DatasetAnimal,
    ProcessedData,
    DatasetSession,
    ProcessingTrackers,
    filter_sessions,
    iterate_sessions,
    discover_projects,
    discover_sessions,
    validate_directory,
    iter_animal_sessions,
    iter_project_animals,
    get_projects_for_animal,
    parse_session_timestamp,
)

# This library drives its own pipeline, so it owns the console state for the runtimes that import it.
if not console.enabled:
    console.enable()

__all__ = [
    "CONFIGURATION_DIRECTORY",
    "CREDENTIALS_DIRECTORY",
    "CREDENTIALS_FILE_REGISTRY",
    "DATASET_MARKER_FILENAME",
    "DESCRIPTOR_REGISTRY",
    "PERSISTENT_DATA_DIRECTORY",
    "PROCESSED_DATA_DIRECTORY",
    "RAW_DATA_DIRECTORY",
    "READ_ASSET_REGISTRY",
    "SESSION_TYPES_USING_VR_TASK",
    "AcquisitionSystems",
    "AnimalData",
    "CredentialsTypes",
    "Cue",
    "DatasetAnimal",
    "DatasetData",
    "DatasetFiles",
    "DatasetSession",
    "Directories",
    "DrugData",
    "ExperimentState",
    "ImplantData",
    "InjectionData",
    "LickTrainingDescriptor",
    "MesoscopeDirectories",
    "MesoscopeExperimentConfiguration",
    "MesoscopeExperimentDescriptor",
    "MesoscopeGasPuffTrial",
    "MesoscopeHardwareState",
    "MesoscopeRawData",
    "MesoscopeRawDataFiles",
    "MesoscopeWaterRewardTrial",
    "ProcedureData",
    "ProcessedData",
    "ProcessingTrackers",
    "ProjectData",
    "RawData",
    "RawDataFiles",
    "ReadAssets",
    "RunTrainingDescriptor",
    "SessionData",
    "SessionTypes",
    "SubjectData",
    "SurgeryData",
    "TaskTemplate",
    "TrialKind",
    "TrialStructure",
    "TriggerType",
    "VREnvironment",
    "WindowCheckingDescriptor",
    "discover_projects",
    "discover_sessions",
    "filter_sessions",
    "get_credentials",
    "get_data_root",
    "get_projects_for_animal",
    "get_task_templates_directory",
    "get_working_directory",
    "iter_animal_sessions",
    "iter_project_animals",
    "iterate_sessions",
    "parse_session_timestamp",
    "resolve_credentials_file",
    "resolve_read_asset",
    "set_credentials",
    "set_data_root",
    "set_task_templates_directory",
    "set_working_directory",
    "validate_directory",
]
