"""Provides configuration utilities shared across all data acquisition systems."""

from __future__ import annotations

from copy import deepcopy
from enum import StrEnum
from pathlib import Path
from collections.abc import Callable

import platformdirs
from ataraxis_base_utilities import LogLevel, console, ensure_directory_exists

from .vr_configuration import TriggerType, TaskTemplate
from .mesoscope_configuration import MesoscopeExperimentConfiguration
from .experiment_configuration import GasPuffTrial, ExperimentState, WaterRewardTrial


class AcquisitionSystems(StrEnum):
    """Defines the data acquisition systems currently supported by the Sollertia platform.

    Each acquisition runtime package owns its own system configuration classes; this enum remains the shared
    vocabulary that identifies which runtime a session or dataset was acquired on.
    """

    MESOSCOPE_VR = "mesoscope"
    """Uses the 2-Photon Random Access Mesoscope (2P-RAM) with Virtual Reality (VR) environments running in Unity game
    engine to conduct experiments."""


type ExperimentConfigFactory = Callable[
    [TaskTemplate, str, dict[str, WaterRewardTrial | GasPuffTrial], float],
    MesoscopeExperimentConfiguration,
]
"""Type alias for experiment configuration factory functions."""

_experiment_config_factory_registry: dict[str, ExperimentConfigFactory] = {}
"""Maps acquisition system names to their experiment configuration factory functions."""

_DEFAULT_STATE_DURATION_S: int = 60
"""Default duration in seconds for each runtime state generated by ``populate_default_experiment_states``."""

_DEFAULT_INITIAL_GUIDED_TRIALS: int = 3
"""Default number of guided trials issued at the start of each reinforcing or aversive runtime state."""

_DEFAULT_RECOVERY_FAILED_THRESHOLD: int = 9
"""Default number of consecutive failed trials that triggers recovery guided trial issuance."""

_DEFAULT_RECOVERY_GUIDED_TRIALS: int = 3
"""Default number of guided trials issued when the recovery threshold is crossed."""


def set_working_directory(path: Path) -> None:
    """Sets the specified directory as the Sollertia platform working directory for the local machine (PC).

    Notes:
        This function caches the path to the working directory in the user's data directory.

        If the input path does not point to an existing directory, the function creates the requested directory.

    Args:
        path: The path to the directory to set as the local Sollertia platform working directory.
    """
    app_dir = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = app_dir.joinpath("working_directory_path.txt")

    ensure_directory_exists(path=path_file)
    ensure_directory_exists(path=path)
    ensure_directory_exists(path=path.joinpath("configuration"))

    with path_file.open(mode="w") as file:
        file.write(str(path))

    console.echo(message=f"Sollertia platform working directory set to: {path}.", level=LogLevel.SUCCESS)


def get_working_directory() -> Path:
    """Resolves and returns the path to the local Sollertia platform working directory.

    Returns:
        The path to the local working directory.

    Raises:
        FileNotFoundError: If the local working directory has not been configured for the host-machine, or if the
            currently configured directory does not exist at the expected path.
    """
    app_dir = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = app_dir.joinpath("working_directory_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the local Sollertia platform working directory, as it has not been set. "
            "Set the local working directory by using the 'sl-configure directory' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        working_directory = Path(file.read().strip())

    if not working_directory.exists():
        message = (
            "Unable to resolve the path to the local Sollertia platform working directory, as the currently configured "
            "directory does not exist at the expected path. Set a new working directory by using the 'sl-configure "
            "directory' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return working_directory


def create_experiment_configuration(
    template: TaskTemplate,
    system: AcquisitionSystems | str,
    unity_scene_name: str,
    default_reward_size_ul: float = 5.0,
    default_reward_tone_duration_ms: int = 300,
    default_puff_duration_ms: int = 100,
    default_occupancy_duration_ms: int = 1000,
) -> MesoscopeExperimentConfiguration:
    """Creates an experiment configuration for the specified acquisition system from a TaskTemplate.

    Args:
        template: The TaskTemplate containing the VR structure (cues, segments, trial zones) of the experiment.
        system: The data acquisition system for which to create the configuration.
        unity_scene_name: The Unity scene name for the experiment. Must match the template's scene file name.
        default_reward_size_ul: Water reward volume in microliters for lick-type trials.
        default_reward_tone_duration_ms: Reward tone duration in milliseconds for lick-type trials.
        default_puff_duration_ms: Gas puff duration in milliseconds for occupancy-type trials.
        default_occupancy_duration_ms: Occupancy threshold duration in milliseconds for occupancy-type trials.

    Returns:
        The experiment configuration for the specified acquisition system.

    Raises:
        ValueError: If the requested acquisition system is not supported by the Sollertia platform.
    """
    system_str = str(system)
    if system_str not in _experiment_config_factory_registry:
        supported_systems = list(_experiment_config_factory_registry.keys())
        message = (
            f"Unable to create the experiment configuration for the acquisition system '{system}'. The specified "
            f"acquisition system is not supported. Currently, only the following acquisition systems are supported: "
            f"{', '.join(supported_systems)}."
        )
        console.error(message=message, error=ValueError)

    trial_structures: dict[str, WaterRewardTrial | GasPuffTrial] = {}
    for trial_name, base_trial in template.trial_structures.items():
        if base_trial.trigger_type == TriggerType.LICK:
            trial_structures[trial_name] = WaterRewardTrial(
                segment_name=base_trial.segment_name,
                stimulus_trigger_zone_start_cm=base_trial.stimulus_trigger_zone_start_cm,
                stimulus_trigger_zone_end_cm=base_trial.stimulus_trigger_zone_end_cm,
                stimulus_location_cm=base_trial.stimulus_location_cm,
                show_stimulus_collision_boundary=base_trial.show_stimulus_collision_boundary,
                trigger_type=base_trial.trigger_type,
                reward_size_ul=default_reward_size_ul,
                reward_tone_duration_ms=default_reward_tone_duration_ms,
            )
        elif base_trial.trigger_type == TriggerType.OCCUPANCY:
            trial_structures[trial_name] = GasPuffTrial(
                segment_name=base_trial.segment_name,
                stimulus_trigger_zone_start_cm=base_trial.stimulus_trigger_zone_start_cm,
                stimulus_trigger_zone_end_cm=base_trial.stimulus_trigger_zone_end_cm,
                stimulus_location_cm=base_trial.stimulus_location_cm,
                show_stimulus_collision_boundary=base_trial.show_stimulus_collision_boundary,
                trigger_type=base_trial.trigger_type,
                puff_duration_ms=default_puff_duration_ms,
                occupancy_duration_ms=default_occupancy_duration_ms,
            )

    # The Callable type alias does not carry parameter names, so the factory must be called with positional arguments.
    factory = _experiment_config_factory_registry[system_str]
    return factory(
        template,
        unity_scene_name,
        trial_structures,
        template.cue_offset_cm,
    )


def populate_default_experiment_states(
    experiment_configuration: MesoscopeExperimentConfiguration,
    state_count: int,
) -> None:
    """Populates the experiment configuration with the requested number of default-valued runtime states.

    Generates `state_count` sequentially numbered runtime states named 'state_1', 'state_2', and so on. Each state uses
    the module-level default duration and is configured with reinforcing or aversive guidance parameters depending on
    the trial types present in the experiment configuration. States are appended to the experiment configuration's
    existing experiment_states mapping.

    Args:
        experiment_configuration: The experiment configuration to extend with default runtime states.
        state_count: The number of runtime states to generate.
    """
    water_reward_count = sum(
        1 for trial in experiment_configuration.trial_structures.values() if isinstance(trial, WaterRewardTrial)
    )
    gas_puff_count = sum(
        1 for trial in experiment_configuration.trial_structures.values() if isinstance(trial, GasPuffTrial)
    )

    for state_index in range(state_count):
        state_name = f"state_{state_index + 1}"
        experiment_configuration.experiment_states[state_name] = ExperimentState(
            experiment_state_code=state_index + 1,
            system_state_code=0,
            state_duration_s=_DEFAULT_STATE_DURATION_S,
            supports_trials=True,
            reinforcing_initial_guided_trials=_DEFAULT_INITIAL_GUIDED_TRIALS if water_reward_count else 0,
            reinforcing_recovery_failed_threshold=_DEFAULT_RECOVERY_FAILED_THRESHOLD if water_reward_count else 0,
            reinforcing_recovery_guided_trials=_DEFAULT_RECOVERY_GUIDED_TRIALS if water_reward_count else 0,
            aversive_initial_guided_trials=_DEFAULT_INITIAL_GUIDED_TRIALS if gas_puff_count else 0,
            aversive_recovery_failed_threshold=_DEFAULT_RECOVERY_FAILED_THRESHOLD if gas_puff_count else 0,
            aversive_recovery_guided_trials=_DEFAULT_RECOVERY_GUIDED_TRIALS if gas_puff_count else 0,
        )


def set_google_credentials_path(path: Path) -> None:
    """Sets the path to the Google Sheets service account credentials .JSON file for the local machine (PC).

    Notes:
        The configured credentials file is used for all future interactions with the Google Sheets API carried
        out from this machine.

    Args:
        path: The path to the .JSON file containing the Google Sheets service account credentials.

    Raises:
        FileNotFoundError: If the specified credentials file does not exist at the provided path.
        ValueError: If the specified file does not have a .json extension.
    """
    if not path.exists():
        message = (
            f"Unable to set the Google Sheets credentials path. The specified file ({path}) does not exist. "
            f"Ensure the .JSON credentials file exists at the specified path before calling this function."
        )
        console.error(message=message, error=FileNotFoundError)

    if path.suffix.lower() != ".json":
        message = (
            f"Unable to set the Google Sheets credentials path. The specified file ({path}) does not have a .json "
            f"extension. Provide the path to the Google Sheets service account credentials .JSON file."
        )
        console.error(message=message, error=ValueError)

    app_dir = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = app_dir.joinpath("google_credentials_path.txt")

    ensure_directory_exists(path=path_file)

    with path_file.open(mode="w") as file:
        file.write(str(path.resolve()))

    console.echo(message=f"Google Sheets credentials path set to: {path.resolve()}.", level=LogLevel.SUCCESS)


def get_google_credentials_path() -> Path:
    """Resolves and returns the path to the Google service account credentials .JSON file.

    Returns:
        The path to the Google service account credentials .JSON file.

    Raises:
        FileNotFoundError: If the Google service account credentials path has not been configured for the host-machine,
            or if the previously configured credentials file does not exist at the expected path.
    """
    app_dir = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = app_dir.joinpath("google_credentials_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the Google account credentials file, as it has not been set. "
            "Set the Google service account credentials path by using the 'sl-configure google' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        credentials_path = Path(file.read().strip())

    if not credentials_path.exists():
        message = (
            f"Unable to resolve the path to the Google account credentials file, as the previously configured "
            f"credentials file does not exist at the expected path ({credentials_path}). Set a new credentials path "
            f"by using the 'sl-configure google' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return credentials_path


def set_task_templates_directory(path: Path) -> None:
    """Sets the path to the sollertia-unity-tasks project's Configurations (Template) directory for the local
    machine (PC).

    Args:
        path: The path to the sollertia-unity-tasks project's Configurations (Template) directory.

    Raises:
        FileNotFoundError: If the specified directory does not exist at the provided path.
        ValueError: If the specified path does not point to a directory.
    """
    if not path.exists():
        message = (
            f"Unable to set the task templates directory path. The specified directory ({path}) does not exist. "
            f"Ensure the directory exists at the specified path before calling this function."
        )
        console.error(message=message, error=FileNotFoundError)

    if not path.is_dir():
        message = (
            f"Unable to set the task templates directory path. The specified path ({path}) does not point to a "
            f"directory. Provide the path to the sollertia-unity-tasks project's Configurations (Template) directory."
        )
        console.error(message=message, error=ValueError)

    app_dir = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = app_dir.joinpath("task_templates_directory_path.txt")

    ensure_directory_exists(path=path_file)

    with path_file.open(mode="w") as file:
        file.write(str(path.resolve()))

    console.echo(message=f"Task templates directory path set to: {path.resolve()}.", level=LogLevel.SUCCESS)


def get_task_templates_directory() -> Path:
    """Resolves and returns the path to the sollertia-unity-tasks project's Configurations (Template) directory.

    Returns:
        The path to the task templates directory.

    Raises:
        FileNotFoundError: If the task templates directory path has not been configured for the host-machine, or if
            the previously configured directory does not exist at the expected path.
    """
    app_dir = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = app_dir.joinpath("task_templates_directory_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the task templates directory, as it has not been set. "
            "Set the task templates directory path by using the 'sl-configure templates' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        templates_directory = Path(file.read().strip())

    if not templates_directory.exists():
        message = (
            f"Unable to resolve the path to the task templates directory, as the previously configured "
            f"directory does not exist at the expected path ({templates_directory}). Set a new directory path "
            f"by using the 'sl-configure templates' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return templates_directory


def _create_mesoscope_experiment_config(
    template: TaskTemplate,
    unity_scene_name: str,
    trial_structures: dict[str, WaterRewardTrial | GasPuffTrial],
    cue_offset_cm: float,
) -> MesoscopeExperimentConfiguration:
    """Creates a Mesoscope-VR experiment configuration from a TaskTemplate.

    Args:
        template: The TaskTemplate containing the VR structure.
        unity_scene_name: The Unity scene name for the experiment.
        trial_structures: The converted trial structures dictionary.
        cue_offset_cm: The cue offset in centimeters.

    Returns:
        The initialized MesoscopeExperimentConfiguration instance.
    """
    return MesoscopeExperimentConfiguration(
        cues=deepcopy(template.cues),
        segments=deepcopy(template.segments),
        trial_structures=trial_structures,
        experiment_states={},
        vr_environment=deepcopy(template.vr_environment),
        unity_scene_name=unity_scene_name,
        cue_offset_cm=cue_offset_cm,
    )


_experiment_config_factory_registry[AcquisitionSystems.MESOSCOPE_VR] = _create_mesoscope_experiment_config
