from pathlib import Path

CONFIGURATION_DIRECTORY: str
CREDENTIALS_DIRECTORY: str

def set_working_directory(path: Path) -> None: ...
def get_working_directory() -> Path: ...
def set_data_root(path: Path) -> None: ...
def get_data_root() -> Path: ...
def set_task_templates_directory(path: Path) -> None: ...
def get_task_templates_directory() -> Path: ...
