"""Provides configuration utilities shared across all data acquisition systems."""

from __future__ import annotations

from enum import StrEnum
from typing import TYPE_CHECKING
from pathlib import Path
from collections.abc import Callable

import platformdirs
from ataraxis_base_utilities import LogLevel, console, ensure_directory_exists

from .vr_configuration import TriggerType, TaskTemplate
from .mesoscope_configuration import MesoscopeExperimentConfiguration
from .experiment_configuration import GasPuffTrial, ExperimentState, WaterRewardTrial

if TYPE_CHECKING:
    from ataraxis_data_structures import YamlConfig


class AcquisitionSystems(StrEnum):
    """Defines the data acquisition systems currently supported by the Sollertia platform.

    Each acquisition runtime package owns its own system configuration classes; this enum remains the shared
    vocabulary that identifies which runtime a session or dataset was acquired on.
    """

    MESOSCOPE_VR = "mesoscope"
    """Uses the 2-Photon Random Access Mesoscope (2P-RAM) with Virtual Reality (VR) environments running in Unity game
    engine to conduct experiments."""


EXPERIMENT_CONFIGURATION_REGISTRY: dict[AcquisitionSystems, type[YamlConfig]] = {
    AcquisitionSystems.MESOSCOPE_VR: MesoscopeExperimentConfiguration,
}
"""Maps each acquisition system to its experiment configuration dataclass. Future acquisition systems register here so
that the configuration schema, read, and write tools can dispatch to the correct dataclass without hard-coding any
single system. ``SessionData.create()`` also consults this registry when caching the per-session experiment
configuration snapshot, so future ExperimentConfiguration classes whose schema omits ``unity_scene_name`` can opt out
of VR template export without modifying the session-creation logic."""


type ExperimentConfigFactory = Callable[
    [str, dict[str, WaterRewardTrial | GasPuffTrial]],
    MesoscopeExperimentConfiguration,
]
"""Callable contract for the per-system factories invoked by ``create_experiment_configuration``."""

_experiment_config_factory_registry: dict[AcquisitionSystems, ExperimentConfigFactory] = {}
"""Maps each acquisition system to its experiment configuration factory function."""

_DEFAULT_STATE_DURATION_S: int = 60
"""Default duration in seconds for each runtime state generated by ``populate_default_experiment_states``."""

_DEFAULT_INITIAL_GUIDED_TRIALS: int = 3
"""Default number of guided trials issued at the start of each reinforcing or aversive runtime state."""

_DEFAULT_RECOVERY_FAILED_THRESHOLD: int = 9
"""Default number of consecutive failed trials that triggers recovery guided trial issuance."""

_DEFAULT_RECOVERY_GUIDED_TRIALS: int = 3
"""Default number of guided trials issued when the recovery threshold is crossed."""


def set_working_directory(path: Path) -> None:
    """Sets the specified directory as the Sollertia platform working directory for the local machine (PC).

    Notes:
        This function caches the path to the working directory in the user's data directory.

        If the input path does not point to an existing directory, the function creates the requested directory.

    Args:
        path: The path to the directory to set as the local Sollertia platform working directory.
    """
    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("working_directory_path.txt")

    ensure_directory_exists(path=path_file)
    ensure_directory_exists(path=path)
    ensure_directory_exists(path=path.joinpath("configuration"))

    with path_file.open(mode="w") as file:
        file.write(str(path))

    console.echo(message=f"Sollertia platform working directory set to: {path}.", level=LogLevel.SUCCESS)


def get_working_directory() -> Path:
    """Resolves and returns the path to the local Sollertia platform working directory.

    Returns:
        The path to the local working directory.

    Raises:
        FileNotFoundError: If the local working directory has not been configured for the host-machine, or if the
            currently configured directory does not exist at the expected path.
    """
    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("working_directory_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the local Sollertia platform working directory, as it has not been set. "
            "Set the local working directory by using the 'slsa configure directory' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        working_directory = Path(file.read().strip())

    if not working_directory.exists():
        message = (
            "Unable to resolve the path to the local Sollertia platform working directory, as the currently configured "
            "directory does not exist at the expected path. Set a new working directory by using the 'slsa configure "
            "directory' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return working_directory


def set_data_root(path: Path) -> None:
    """Sets the specified directory as the local machine's Sollertia platform data root.

    The data root is the directory under which all project directories, and therefore all animal and session
    directories, are stored on this machine. Persisting it lets the discovery and inventory assets resolve the
    project hierarchy without the caller supplying the root each time.

    Notes:
        This function caches the path to the data root in the user's data directory.

        If the input path does not point to an existing directory, the function creates the requested directory.

    Args:
        path: The path to the directory to set as the local Sollertia platform data root.
    """
    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("data_root_path.txt")

    ensure_directory_exists(path=path_file)
    ensure_directory_exists(path=path)

    with path_file.open(mode="w") as file:
        file.write(str(path))

    console.echo(message=f"Sollertia platform data root set to: {path}.", level=LogLevel.SUCCESS)


def get_data_root() -> Path:
    """Resolves and returns the path to the local machine's Sollertia platform data root.

    Returns:
        The path to the local data root, the directory under which all project directories are stored.

    Raises:
        FileNotFoundError: If the local data root has not been configured for the host-machine, or if the currently
            configured directory does not exist at the expected path.
    """
    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("data_root_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the local Sollertia platform data root, as it has not been set. "
            "Set the local data root by using the 'slsa configure data-root' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        data_root = Path(file.read().strip())

    if not data_root.exists():
        message = (
            "Unable to resolve the path to the local Sollertia platform data root, as the currently configured "
            "directory does not exist at the expected path. Set a new data root by using the 'slsa configure "
            "data-root' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return data_root


def create_experiment_configuration(
    template: TaskTemplate,
    system: AcquisitionSystems | str,
    unity_scene_name: str,
    default_reward_size_ul: float = 5.0,
    default_reward_tone_duration_ms: int = 300,
    default_puff_duration_ms: int = 100,
    default_occupancy_duration_ms: int = 1000,
) -> MesoscopeExperimentConfiguration:
    """Creates an experiment configuration for the specified acquisition system from a TaskTemplate.

    Args:
        template: The TaskTemplate containing the VR structure (cues, trial zones) of the experiment.
        system: The data acquisition system for which to create the configuration.
        unity_scene_name: The Unity scene name for the experiment. This should match the template YAML file name so
            SessionData.create() can locate the corresponding VR template during snapshot export. Matching is the
            caller's responsibility and is not validated by this function.
        default_reward_size_ul: Water reward volume in microliters for lick-type trials.
        default_reward_tone_duration_ms: Reward tone duration in milliseconds for lick-type trials.
        default_puff_duration_ms: Gas puff duration in milliseconds for occupancy-type trials.
        default_occupancy_duration_ms: Occupancy threshold duration in milliseconds for occupancy-type trials.

    Returns:
        The experiment configuration for the specified acquisition system.

    Raises:
        ValueError: If the requested acquisition system is not supported by the Sollertia platform.
    """
    try:
        acquisition_system: AcquisitionSystems | None = AcquisitionSystems(system)
    except ValueError:
        acquisition_system = None

    if acquisition_system is None or acquisition_system not in _experiment_config_factory_registry:
        supported_systems = ", ".join(member.value for member in _experiment_config_factory_registry)
        message = (
            f"Unable to create the experiment configuration for the acquisition system '{system}'. The specified "
            f"acquisition system is not supported. Currently, only the following acquisition systems are supported: "
            f"{supported_systems}."
        )
        console.error(message=message, error=ValueError)

    trial_structures: dict[str, WaterRewardTrial | GasPuffTrial] = {}
    for trial_name, trial_structure in template.trial_structures.items():
        if trial_structure.trigger_type == TriggerType.LICK:
            trial_structures[trial_name] = WaterRewardTrial(
                reward_size_ul=default_reward_size_ul,
                reward_tone_duration_ms=default_reward_tone_duration_ms,
            )
        elif trial_structure.trigger_type == TriggerType.OCCUPANCY:
            trial_structures[trial_name] = GasPuffTrial(
                puff_duration_ms=default_puff_duration_ms,
                occupancy_duration_ms=default_occupancy_duration_ms,
            )

    # The Callable type alias does not carry parameter names, so the factory must be called with positional arguments.
    factory = _experiment_config_factory_registry[acquisition_system]
    return factory(
        unity_scene_name,
        trial_structures,
    )


def populate_default_experiment_states(
    experiment_configuration: MesoscopeExperimentConfiguration,
    state_count: int,
) -> None:
    """Populates the experiment configuration with the requested number of default-valued runtime states.

    Generates ``state_count`` sequentially numbered runtime states named 'state_1', 'state_2', and so on. Each
    state uses the module-level default duration and is configured with reinforcing or aversive guidance parameters
    depending on the trial types present in the experiment configuration. States are appended to the experiment
    configuration's existing experiment_states mapping.

    Args:
        experiment_configuration: The experiment configuration to extend with default runtime states.
        state_count: The number of runtime states to generate.
    """
    water_reward_count = sum(
        1 for trial in experiment_configuration.trial_structures.values() if isinstance(trial, WaterRewardTrial)
    )
    gas_puff_count = sum(
        1 for trial in experiment_configuration.trial_structures.values() if isinstance(trial, GasPuffTrial)
    )

    for state_index in range(state_count):
        state_name = f"state_{state_index + 1}"
        experiment_configuration.experiment_states[state_name] = ExperimentState(
            experiment_state_code=state_index + 1,
            system_state_code=0,
            state_duration_s=_DEFAULT_STATE_DURATION_S,
            supports_trials=True,
            reinforcing_initial_guided_trials=_DEFAULT_INITIAL_GUIDED_TRIALS if water_reward_count else 0,
            reinforcing_recovery_failed_threshold=_DEFAULT_RECOVERY_FAILED_THRESHOLD if water_reward_count else 0,
            reinforcing_recovery_guided_trials=_DEFAULT_RECOVERY_GUIDED_TRIALS if water_reward_count else 0,
            aversive_initial_guided_trials=_DEFAULT_INITIAL_GUIDED_TRIALS if gas_puff_count else 0,
            aversive_recovery_failed_threshold=_DEFAULT_RECOVERY_FAILED_THRESHOLD if gas_puff_count else 0,
            aversive_recovery_guided_trials=_DEFAULT_RECOVERY_GUIDED_TRIALS if gas_puff_count else 0,
        )


def set_google_credentials_path(path: Path) -> None:
    """Sets the path to the Google Sheets service account credentials .JSON file for the local machine (PC).

    Notes:
        The configured credentials file is used for all future interactions with the Google Sheets API carried
        out from this machine.

    Args:
        path: The path to the .JSON file containing the Google Sheets service account credentials.

    Raises:
        FileNotFoundError: If the specified credentials file does not exist at the provided path.
        ValueError: If the specified file does not have a .json extension.
    """
    if not path.exists():
        message = (
            f"Unable to set the Google Sheets credentials path. The specified file ({path}) does not exist. "
            f"Ensure the .JSON credentials file exists at the specified path before calling this function."
        )
        console.error(message=message, error=FileNotFoundError)

    if path.suffix.lower() != ".json":
        message = (
            f"Unable to set the Google Sheets credentials path. The specified file ({path}) does not have a .json "
            f"extension. Provide the path to the Google Sheets service account credentials .JSON file."
        )
        console.error(message=message, error=ValueError)

    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("google_credentials_path.txt")

    ensure_directory_exists(path=path_file)

    with path_file.open(mode="w") as file:
        file.write(str(path.resolve()))

    console.echo(message=f"Google Sheets credentials path set to: {path.resolve()}.", level=LogLevel.SUCCESS)


def get_google_credentials_path() -> Path:
    """Resolves and returns the path to the Google service account credentials .JSON file.

    Returns:
        The path to the Google service account credentials .JSON file.

    Raises:
        FileNotFoundError: If the Google service account credentials path has not been configured for the host-machine,
            or if the previously configured credentials file does not exist at the expected path.
    """
    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("google_credentials_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the Google account credentials file, as it has not been set. "
            "Set the Google service account credentials path by using the 'slsa configure google' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        credentials_path = Path(file.read().strip())

    if not credentials_path.exists():
        message = (
            f"Unable to resolve the path to the Google account credentials file, as the previously configured "
            f"credentials file does not exist at the expected path ({credentials_path}). Set a new credentials path "
            f"by using the 'slsa configure google' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return credentials_path


def set_task_templates_directory(path: Path) -> None:
    """Sets the path to the sollertia-unity-tasks project's Configurations (Template) directory.

    Persists the path under ``platformdirs``-managed application data so it is reused by subsequent ``slsa mcp``
    sessions on the same local machine (PC).

    Args:
        path: The path to the sollertia-unity-tasks project's Configurations (Template) directory.

    Raises:
        FileNotFoundError: If the specified directory does not exist at the provided path.
        ValueError: If the specified path does not point to a directory.
    """
    if not path.exists():
        message = (
            f"Unable to set the task templates directory path. The specified directory ({path}) does not exist. "
            f"Ensure the directory exists at the specified path before calling this function."
        )
        console.error(message=message, error=FileNotFoundError)

    if not path.is_dir():
        message = (
            f"Unable to set the task templates directory path. The specified path ({path}) does not point to a "
            f"directory. Provide the path to the sollertia-unity-tasks project's Configurations (Template) directory."
        )
        console.error(message=message, error=ValueError)

    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("task_templates_directory_path.txt")

    ensure_directory_exists(path=path_file)

    with path_file.open(mode="w") as file:
        file.write(str(path.resolve()))

    console.echo(message=f"Task templates directory path set to: {path.resolve()}.", level=LogLevel.SUCCESS)


def get_task_templates_directory() -> Path:
    """Resolves and returns the path to the sollertia-unity-tasks project's Configurations (Template) directory.

    Returns:
        The path to the task templates directory.

    Raises:
        FileNotFoundError: If the task templates directory path has not been configured for the host-machine, or if
            the previously configured directory does not exist at the expected path.
    """
    application_directory = Path(platformdirs.user_data_dir(appname="sollertia_data", appauthor="sollertia"))
    path_file = application_directory.joinpath("task_templates_directory_path.txt")

    if not path_file.exists():
        message = (
            "Unable to resolve the path to the task templates directory, as it has not been set. "
            "Set the task templates directory path by using the 'slsa configure templates' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    with path_file.open() as file:
        templates_directory = Path(file.read().strip())

    if not templates_directory.exists():
        message = (
            f"Unable to resolve the path to the task templates directory, as the previously configured "
            f"directory does not exist at the expected path ({templates_directory}). Set a new directory path "
            f"by using the 'slsa configure templates' CLI command."
        )
        console.error(message=message, error=FileNotFoundError)

    return templates_directory


def _create_mesoscope_experiment_config(
    unity_scene_name: str,
    trial_structures: dict[str, WaterRewardTrial | GasPuffTrial],
) -> MesoscopeExperimentConfiguration:
    """Creates a Mesoscope-VR experiment configuration.

    Args:
        unity_scene_name: The Unity scene name for the experiment.
        trial_structures: The per-trial reward and puff parameters, keyed by trial name.

    Returns:
        The experiment configuration populated with the given trial structures and an empty experiment-state map.
    """
    return MesoscopeExperimentConfiguration(
        trial_structures=trial_structures,
        experiment_states={},
        unity_scene_name=unity_scene_name,
    )


_experiment_config_factory_registry[AcquisitionSystems.MESOSCOPE_VR] = _create_mesoscope_experiment_config
