from pathlib import Path
from dataclasses import field, dataclass

from ataraxis_data_structures import YamlConfig

from .vr_configuration import (
    Cue as Cue,
    Segment as Segment,
    VREnvironment as VREnvironment,
)
from .experiment_configuration import (
    GasPuffTrial as GasPuffTrial,
    ExperimentState as ExperimentState,
    WaterRewardTrial as WaterRewardTrial,
)

@dataclass
class MesoscopeExperimentConfiguration(YamlConfig):
    cues: list[Cue]
    segments: list[Segment]
    trial_structures: dict[str, WaterRewardTrial | GasPuffTrial]
    experiment_states: dict[str, ExperimentState]
    vr_environment: VREnvironment
    unity_scene_name: str
    cue_offset_cm: float = ...
    @property
    def _cue_by_name(self) -> dict[str, Cue]: ...
    @property
    def _cue_name_to_code(self) -> dict[str, int]: ...
    @property
    def _segment_by_name(self) -> dict[str, Segment]: ...
    def _get_segment_length_cm(self, segment_name: str) -> float: ...
    def _get_segment_cue_codes(self, segment_name: str) -> list[int]: ...
    def __post_init__(self) -> None: ...

@dataclass(slots=True)
class MesoscopeFileSystem:
    root_directory: Path = ...
    server_directory: Path = ...
    nas_directory: Path = ...
    mesoscope_directory: Path = ...

@dataclass(slots=True)
class MesoscopeGoogleSheets:
    surgery_sheet_id: str = ...
    water_log_sheet_id: str = ...

@dataclass(slots=True)
class MesoscopeCameras:
    face_camera_index: int = ...
    body_camera_index: int = ...
    face_camera_quantization: int = ...
    face_camera_preset: int = ...
    body_camera_quantization: int = ...
    body_camera_preset: int = ...

@dataclass(slots=True)
class MesoscopeMicroControllers:
    actor_port: str = ...
    sensor_port: str = ...
    encoder_port: str = ...
    keepalive_interval_ms: int = ...
    minimum_brake_strength_g_cm: float = ...
    maximum_brake_strength_g_cm: float = ...
    wheel_diameter_cm: float = ...
    lick_threshold_adc: int = ...
    lick_signal_threshold_adc: int = ...
    lick_delta_threshold_adc: int = ...
    lick_averaging_pool_size: int = ...
    torque_baseline_voltage_adc: int = ...
    torque_maximum_voltage_adc: int = ...
    torque_sensor_capacity_g_cm: float = ...
    torque_report_cw: bool = ...
    torque_report_ccw: bool = ...
    torque_signal_threshold_adc: int = ...
    torque_delta_threshold_adc: int = ...
    torque_averaging_pool_size: int = ...
    wheel_encoder_ppr: int = ...
    wheel_encoder_report_cw: bool = ...
    wheel_encoder_report_ccw: bool = ...
    wheel_encoder_delta_threshold_pulse: int = ...
    wheel_encoder_polling_delay_us: int = ...
    cm_per_unity_unit: float = ...
    screen_trigger_pulse_duration_ms: int = ...
    sensor_polling_delay_ms: int = ...
    mesoscope_frame_averaging_pool_size: int = ...
    valve_calibration_data: dict[int | float, int | float] | tuple[tuple[int | float, int | float], ...] = ...

@dataclass(slots=True)
class MesoscopeExternalAssets:
    headbar_port: str = ...
    lickport_port: str = ...
    wheel_port: str = ...
    unity_ip: str = ...
    unity_port: int = ...

@dataclass
class MesoscopeSystemConfiguration(YamlConfig):
    name: str = ...
    filesystem: MesoscopeFileSystem = field(default_factory=MesoscopeFileSystem)
    sheets: MesoscopeGoogleSheets = field(default_factory=MesoscopeGoogleSheets)
    cameras: MesoscopeCameras = field(default_factory=MesoscopeCameras)
    microcontrollers: MesoscopeMicroControllers = field(default_factory=MesoscopeMicroControllers)
    assets: MesoscopeExternalAssets = field(default_factory=MesoscopeExternalAssets)
    def __post_init__(self) -> None: ...
    def save(self, path: Path) -> None: ...
