from typing import Literal
from pathlib import Path

from ..enums import CredentialsTypes as CredentialsTypes
from .mcp_server import run_server as run_server
from ..credentials import (
    get_credentials as get_credentials,
    set_credentials as set_credentials,
)
from ..configuration import (
    get_data_root as get_data_root,
    set_data_root as set_data_root,
    get_working_directory as get_working_directory,
    set_working_directory as set_working_directory,
    get_task_templates_directory as get_task_templates_directory,
    set_task_templates_directory as set_task_templates_directory,
)
from ..data_hierarchy import (
    ProjectData as ProjectData,
    discover_projects as discover_projects,
)

_CONTEXT_SETTINGS: dict[str, int]

def slsa_cli() -> None: ...
def run_mcp_server(transport: Literal["stdio", "sse", "streamable-http"]) -> None: ...
def get_group() -> None: ...
def get_directory() -> None: ...
def get_data_root_path() -> None: ...
def get_credentials_path(category: str) -> None: ...
def get_templates_directory() -> None: ...
def get_projects() -> None: ...
def get_experiments(project: str) -> None: ...
def configure_group() -> None: ...
def configure_directory(directory: Path) -> None: ...
def configure_data_root(directory: Path) -> None: ...
def configure_credentials(category: str, file: Path) -> None: ...
def configure_task_templates_directory(directory: Path) -> None: ...
def configure_project(project: str) -> None: ...
