from typing import Any

from ataraxis_data_structures import YamlConfig as YamlConfig

from ..enums import (
    ReadAssets as ReadAssets,
    SessionTypes as SessionTypes,
    CredentialsTypes as CredentialsTypes,
    AcquisitionSystems as AcquisitionSystems,
)
from ..registries import (
    DESCRIPTOR_REGISTRY as DESCRIPTOR_REGISTRY,
    READ_ASSET_REGISTRY as READ_ASSET_REGISTRY,
    SYSTEM_SESSION_TYPES as SYSTEM_SESSION_TYPES,
    CREDENTIALS_FILE_REGISTRY as CREDENTIALS_FILE_REGISTRY,
    EXPERIMENT_CONFIGURATION_REGISTRY as EXPERIMENT_CONFIGURATION_REGISTRY,
)
from ..credentials import (
    get_credentials as get_credentials,
    set_credentials as set_credentials,
)
from .mcp_instance import (
    mcp as mcp,
    read_yaml as read_yaml,
    serialize as serialize,
    ok_response as ok_response,
    safe_iterdir as safe_iterdir,
    error_response as error_response,
    describe_dataclass as describe_dataclass,
    write_yaml_validated as write_yaml_validated,
    resolve_root_directory as resolve_root_directory,
    collect_field_dataclasses as collect_field_dataclasses,
)
from ..configuration import (
    CONFIGURATION_DIRECTORY as CONFIGURATION_DIRECTORY,
    Cue as Cue,
    TriggerType as TriggerType,
    TaskTemplate as TaskTemplate,
    VREnvironment as VREnvironment,
    TrialStructure as TrialStructure,
    get_data_root as get_data_root,
    set_data_root as set_data_root,
    get_working_directory as get_working_directory,
    set_working_directory as set_working_directory,
    get_task_templates_directory as get_task_templates_directory,
    set_task_templates_directory as set_task_templates_directory,
)
from ..data_hierarchy import ProjectData as ProjectData

def get_platform_environment_status_tool() -> dict[str, Any]: ...
def read_working_directory_tool() -> dict[str, Any]: ...
def set_working_directory_tool(directory: str) -> dict[str, Any]: ...
def read_data_root_tool() -> dict[str, Any]: ...
def set_data_root_tool(directory: str) -> dict[str, Any]: ...
def create_project_tool(project_name: str, root_directory: str | None = None) -> dict[str, Any]: ...
def read_credentials_tool(credentials: str) -> dict[str, Any]: ...
def set_credentials_tool(credentials: str, file_path: str) -> dict[str, Any]: ...
def read_task_templates_directory_tool() -> dict[str, Any]: ...
def set_task_templates_directory_tool(directory: str) -> dict[str, Any]: ...
def discover_templates_tool() -> dict[str, Any]: ...
def read_template_tool(file_path: str) -> dict[str, Any]: ...
def write_template_tool(
    file_path: str, template_payload: dict[str, Any], *, overwrite: bool = False
) -> dict[str, Any]: ...
def validate_template_tool(file_path: str) -> dict[str, Any]: ...
def describe_template_schema_tool() -> dict[str, Any]: ...
def discover_experiments_tool(root_directory: str, project: str | None = None) -> dict[str, Any]: ...
def read_experiment_configuration_tool(file_path: str, acquisition_system: str) -> dict[str, Any]: ...
def write_experiment_configuration_tool(
    file_path: str, acquisition_system: str, configuration_payload: dict[str, Any], *, overwrite: bool = False
) -> dict[str, Any]: ...
def create_experiment_from_vr_template_tool(
    file_path: str, acquisition_system: str, template_path: str, state_count: int = 1, *, overwrite: bool = False
) -> dict[str, Any]: ...
def validate_experiment_configuration_tool(file_path: str, acquisition_system: str) -> dict[str, Any]: ...
def describe_experiment_configuration_schema_tool(acquisition_system: str) -> dict[str, Any]: ...
def list_supported_session_types_tool(acquisition_system: str | None = None) -> dict[str, Any]: ...
def list_session_type_support_tool() -> dict[str, Any]: ...
def list_supported_acquisition_systems_tool() -> dict[str, Any]: ...
def list_supported_data_assets_tool() -> dict[str, Any]: ...
def list_supported_credentials_tool() -> dict[str, Any]: ...
def list_supported_trial_types_tool(acquisition_system: str) -> dict[str, Any]: ...
def list_supported_trigger_types_tool() -> dict[str, Any]: ...
def _resolve_experiment_configuration_class(acquisition_system: str) -> type[YamlConfig] | dict[str, Any]: ...
