from typing import Any
from pathlib import Path

from ataraxis_data_structures import YamlConfig as YamlConfig

from .mcp_instance import (
    CONFIGURATION_DIR as CONFIGURATION_DIR,
    DESCRIPTOR_REGISTRY as DESCRIPTOR_REGISTRY,
    INCOMPLETE_SESSION_MARKER as INCOMPLETE_SESSION_MARKER,
    mcp as mcp,
    read_yaml as read_yaml,
    serialize as serialize,
    ok_response as ok_response,
    safe_iterdir as safe_iterdir,
    error_response as error_response,
    describe_dataclass as describe_dataclass,
    write_yaml_validated as write_yaml_validated,
    resolve_root_directory as resolve_root_directory,
)
from ..data_classes import (
    DrugData as DrugData,
    ImplantData as ImplantData,
    SessionData as SessionData,
    SubjectData as SubjectData,
    SurgeryData as SurgeryData,
    RawDataFiles as RawDataFiles,
    SessionTypes as SessionTypes,
    InjectionData as InjectionData,
    ProcedureData as ProcedureData,
    MesoscopeHardwareState as MesoscopeHardwareState,
    filter_sessions as filter_sessions,
    session_root_from_marker as session_root_from_marker,
)
from ..configuration import (
    MesoscopeExperimentConfiguration as MesoscopeExperimentConfiguration,
    get_working_directory as get_working_directory,
)

def discover_projects_tool(root_directory: str | None = None) -> dict[str, Any]: ...
def discover_animals_tool(project: str, root_directory: str | None = None) -> dict[str, Any]: ...
def discover_sessions_tool(
    root_directory: str | None = None,
    project: str | None = None,
    animal_id: str | None = None,
    session_types: list[str] | None = None,
) -> dict[str, Any]: ...
def filter_sessions_tool(
    sessions: list[dict[str, Any]],
    start_date: str | None = None,
    end_date: str | None = None,
    include_sessions: list[str] | None = None,
    exclude_sessions: list[str] | None = None,
    include_animals: list[str] | None = None,
    exclude_animals: list[str] | None = None,
    *,
    utc_timezone: bool = True,
) -> dict[str, Any]: ...
def discover_session_descriptors_tool(session_path: str) -> dict[str, Any]: ...
def discover_subjects_tool(root_directory: str, project: str | None = None) -> dict[str, Any]: ...
def read_session_data_tool(session_path: str) -> dict[str, Any]: ...
def read_session_descriptor_tool(session_path: str) -> dict[str, Any]: ...
def read_session_hardware_state_tool(session_path: str) -> dict[str, Any]: ...
def read_session_experiment_configuration_tool(session_path: str) -> dict[str, Any]: ...
def read_subject_tool(subject_id: str, project: str | None = None) -> dict[str, Any]: ...
def read_subject_surgery_tool(subject_id: str, project: str | None = None) -> dict[str, Any]: ...
def read_subject_implants_tool(subject_id: str, project: str | None = None) -> dict[str, Any]: ...
def read_subject_injections_tool(subject_id: str, project: str | None = None) -> dict[str, Any]: ...
def read_subject_drugs_tool(subject_id: str, project: str | None = None) -> dict[str, Any]: ...
def read_subject_procedure_tool(subject_id: str, project: str | None = None) -> dict[str, Any]: ...
def write_session_descriptor_tool(
    session_path: str, descriptor_payload: dict[str, Any], *, overwrite: bool = True
) -> dict[str, Any]: ...
def write_session_hardware_state_tool(
    session_path: str, hardware_state_payload: dict[str, Any], *, overwrite: bool = True
) -> dict[str, Any]: ...
def validate_session_tool(session_path: str) -> dict[str, Any]: ...
def get_session_status_tool(session_path: str) -> dict[str, Any]: ...
def get_batch_session_status_overview_tool(root_directory: str | None = None) -> dict[str, Any]: ...
def describe_session_descriptor_schema_tool(session_type: str) -> dict[str, Any]: ...
def describe_session_hardware_state_schema_tool() -> dict[str, Any]: ...
def describe_surgery_schema_tool() -> dict[str, Any]: ...
def _resolve_session_root(session_path: str) -> tuple[Path | None, dict[str, Any] | None]: ...
def _load_session_summary(marker: Path) -> dict[str, Any]: ...
def _find_descriptor_for_session(
    session_root: Path, session_type: SessionTypes
) -> tuple[Path | None, type[YamlConfig]]: ...
def _resolve_surgery_path(
    subject_id: str, project: str | None = None, root_directory: str | None = None
) -> tuple[Path | None, dict[str, Any] | None]: ...
