from typing import Any

from .mcp_instance import (
    mcp as mcp,
    error_response as error_response,
)

_UNITY_BRIDGE_URL: str

def generate_task_prefab_tool(template_name: str, save_path: str | None = None) -> dict[str, Any]: ...
def inspect_prefab_tool(prefab_path: str) -> dict[str, Any]: ...
def validate_prefab_against_template_tool(template_name: str) -> dict[str, Any]: ...
def list_unity_assets_tool(
    asset_type: str = "Prefab", search_path: str = "Assets/InfiniteCorridorTask"
) -> dict[str, Any]: ...
def list_scenes_tool() -> dict[str, Any]: ...
def open_scene_tool(scene_path: str) -> dict[str, Any]: ...
def create_scene_tool(scene_name: str, task_prefab_path: str | None = None) -> dict[str, Any]: ...
def enter_play_mode_tool() -> dict[str, Any]: ...
def exit_play_mode_tool() -> dict[str, Any]: ...
def get_play_state_tool() -> dict[str, Any]: ...
def _unity_relay(tool: str, arguments: dict[str, Any] | None = None) -> dict[str, Any]: ...
