from typing import Any, Literal

from .mcp_instance import (
    mcp as mcp,
    error_response as error_response,
)

_UNITY_BRIDGE_URL: str
_UNITY_BRIDGE_TIMEOUT: int

def create_task_tool(
    template_name: str, unsaved_changes: Literal["save", "discard"] | None = None
) -> dict[str, Any]: ...
def delete_task_tool(template_name: str) -> dict[str, Any]: ...
def inspect_prefab_tool(prefab_path: str) -> dict[str, Any]: ...
def clone_zone_prefab_tool(
    source_prefab: str,
    destination_prefab: str,
    root_script: str | None = None,
    regions: list[dict[str, Any]] | None = None,
    *,
    overwrite: bool = False,
) -> dict[str, Any]: ...
def delete_asset_tool(asset_path: str) -> dict[str, Any]: ...
def list_assets_tool(
    asset_type: str = "Prefab", search_path: str = "Assets/InfiniteCorridorTask"
) -> dict[str, Any]: ...
def refresh_assets_tool() -> dict[str, Any]: ...
def list_scenes_tool() -> dict[str, Any]: ...
def open_scene_tool(scene_path: str, unsaved_changes: Literal["save", "discard"] | None = None) -> dict[str, Any]: ...
def save_scene_tool() -> dict[str, Any]: ...
def inspect_scene_tool() -> dict[str, Any]: ...
def enter_play_mode_tool() -> dict[str, Any]: ...
def exit_play_mode_tool() -> dict[str, Any]: ...
def get_play_state_tool() -> dict[str, Any]: ...
def read_task_parameters_tool() -> dict[str, Any]: ...
def write_task_parameters_tool(
    actor: dict[str, Any] | None = None,
    mqtt: dict[str, Any] | None = None,
    display: dict[str, Any] | None = None,
    camera_mapping: list[dict[str, Any]] | None = None,
    task: dict[str, Any] | None = None,
) -> dict[str, Any]: ...
def refresh_monitors_tool() -> dict[str, Any]: ...
def read_console_tool(
    level: Literal["all", "log", "warning", "error"] = "all", limit: int = 100, since_sequence: int | None = None
) -> dict[str, Any]: ...
def _unity_relay(tool: str, arguments: dict[str, Any] | None = None) -> dict[str, Any]: ...
