from typing import Literal
from pathlib import Path
from datetime import datetime
from collections.abc import Iterable, Iterator

from .session_data import (
    SessionData as SessionData,
    RawDataFiles as RawDataFiles,
)
from ..configuration import CONFIGURATION_DIRECTORY as CONFIGURATION_DIRECTORY
from .project_hierarchy import (
    DATASET_MARKER_FILENAME as DATASET_MARKER_FILENAME,
    AnimalData as AnimalData,
    ProjectData as ProjectData,
)

_SESSION_NAME_COMPONENTS: int

def validate_directory(directory: str) -> str | None: ...
def iterate_sessions(root_path: Path) -> Iterator[SessionData]: ...
def discover_sessions(root_path: Path) -> list[Path]: ...
def get_session_root_from_marker(marker: Path) -> Path: ...
def discover_projects(
    root_path: Path, strategy: Literal["markers", "directories"] = "markers"
) -> list[ProjectData]: ...
def iter_project_animals(project: ProjectData) -> Iterator[AnimalData]: ...
def iter_animal_sessions(animal: AnimalData) -> Iterator[Path]: ...
def get_projects_for_animal(root_path: Path, animal_id: str) -> tuple[str, ...]: ...
def filter_sessions(
    sessions: Iterable[tuple[str, str]],
    *,
    start_date: str | None = None,
    end_date: str | None = None,
    include_sessions: set[str] | None = None,
    exclude_sessions: set[str] | None = None,
    include_animals: set[str] | None = None,
    exclude_animals: set[str] | None = None,
    utc_timezone: bool = True,
) -> set[tuple[str, str]]: ...
def parse_session_timestamp(session_name: str, *, utc_timezone: bool = True) -> datetime | None: ...
def _discover_projects_by_directory(root_path: Path) -> list[ProjectData]: ...
def _is_animal_directory(path: Path) -> bool: ...
def _parse_date_boundary(date_string: str, *, is_end_date: bool = False, utc_timezone: bool = True) -> datetime: ...
